version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3333:3333" # Uygulamanızın çalıştığı port
    depends_on:
      - db

  db:
    image: postgres:15.7
    restart: always
    environment:
      POSTGRES_DB: bakidatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Host ve konteyner portlarını eşleştir
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: